const DEFAULT_BOT_REQUEST_TIMEOUT_MS = 2500;
const LEVEL8_BOT_REQUEST_TIMEOUT_MS = 5000;
const LEVEL9_BOT_REQUEST_TIMEOUT_MS = 8000;
const LEVEL10_BOT_REQUEST_TIMEOUT_MS = 15000;
const LEVEL11_BOT_REQUEST_TIMEOUT_MS = 18000;
const LEVEL12_BOT_REQUEST_TIMEOUT_MS = 20000;

export function getBotRequestTimeoutMs(level: number): number {
  if (level >= 12) return LEVEL12_BOT_REQUEST_TIMEOUT_MS;
  if (level >= 11) return LEVEL11_BOT_REQUEST_TIMEOUT_MS;
  if (level >= 10) return LEVEL10_BOT_REQUEST_TIMEOUT_MS;
  if (level >= 9) return LEVEL9_BOT_REQUEST_TIMEOUT_MS;
  if (level >= 8) return LEVEL8_BOT_REQUEST_TIMEOUT_MS;
  return DEFAULT_BOT_REQUEST_TIMEOUT_MS;
}
